RKAdmin/Models/TransportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RKAdmin.Models
{
    public class TransportViewModel
    {
        public int Id { get; set; }

        public string Code { get; set; }

        public TransportRouteViewModel Route { get; set; }

        public TransportTypeViewModel Type { get; set; }

    }
}

RKAdmin/Controllers/TransportsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using DataModel;
using DataModel.Models.RozumnaKraina;
using RKAdmin.Models;

namespace RKAdmin.Controllers
{
    [Authorize(Roles = "Адміністратор, Диспетчер")]
    public class TransportsController : BaseController
    {
        public TransportsController(SkargaBotContext db) : base(db)
        {
        }

        public async Task<JsonResult> GetRoutes(int type)
        {
            var routes = await Db.RKDTransportRoutes.Where(_ => _.TypeId == type).Select(_ => new {_.Id, _.Name}).ToListAsync();
            return Json(routes, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Index()
        {
            var model = await Db.RKDTransports.ProjectToListAsync<TransportViewModel>();

            var rKDTransports = Db.RKDTransports.Include(d => d.Route).Include(d => d.Type);
            var transportsViewModel = await rKDTransports.Select(_ => new TransportViewModel
            {
                Id = _.Id,
                Code = _.Code,
                Route = new TransportRouteViewModel
                {
                    Name = _.Route.Name,
                    Id = _.Route.Id,
                    StartStation = _.Route.StartStation,
                    StopStation = _.Route.StopStation
                },
                Type = new TransportTypeViewModel
                {
                    Id = _.Type.Id,
                    Name = _.Type.Name
                }
            }).ToListAsync();

            return View(transportsViewModel);
        }

        public async Task<ActionResult> Add()
        {
            /*var routes = Db.RKDTransportRoutes
               .Select(s => new
               {
                   Id = s.Id,
                               //should be researched how to display this field in dropdown, the value might be too long
                               Description = s.StartStation + " - " + s.StopStation
               }).ToList();*/

            ViewBag.RouteId = new SelectList(Db.RKDTransportRoutes, "Id", "name");
            ViewBag.TypeId = new SelectList(Db.RKDTransportTypes, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(TransportViewModel model)
        {
            var item = Mapper.Map<DemoTransport>(model);

            if (model.Route.Id != null)
            {
                item.Route.TypeId = item.TypeId;
                Db.RKDTransportRoutes.Attach(item.Route);
            }
            else
            {
                item.Route = null;
            }

            Db.RKDTransportTypes.Attach(item.Type);

            Db.RKDTransports.Add(item);
            await Db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int id)
        {
            var item =
                await Db.RKDTransports.ProjectToSingleOrDefaultAsync<DemoTransport, TransportViewModel>(_ =>
                    _.Id == id);

            if (item == null)
                return HttpNotFound();

            /*var routes = Db.RKDTransportRoutes
               .Select(s => new
               {
                   Id = s.Id,
                   //should be researched how to display this field in dropdown, the value might be too long
                   Description = s.StartStation + " - " + s.StopStation
               }).ToList();*/

            ViewBag.RouteId = new SelectList(Db.RKDTransportRoutes, "Id", "Name", item.Route?.Id);
            ViewBag.TypeId = new SelectList(Db.RKDTransportTypes, "Id", "Name", item.Type.Id);

            return View(item);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(TransportViewModel model)
        {
            var item = Mapper.Map<DemoTransport>(model);

            if (item == null)
                return HttpNotFound();

            if (model.Route.Id != null)
                Db.RKDTransportRoutes.Attach(item.Route);
            else
            {
                item.Route = null;
            }

            Db.RKDTransportTypes.Attach(item.Type);

            Db.Entry(item).State = EntityState.Modified;

            await Db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var item = await Db.RKDTransports.SingleOrDefaultAsync(_ => _.Id == id);

            //TODO should be fixed (remove TypeId field from Route table)
            item.Route.TypeId = item.TypeId;

            if (item == null)
                return HttpNotFound();

            Db.RKDTransports.Remove(item);
            await Db.SaveChangesAsync();
            return new EmptyResult();
        }
    }
}

RKAdmin/Views/Transports/Add.cshtml
@{
    ViewBag.Title = "Транспорт";
    ViewBag.Subtitle = "";
}

@model RKAdmin.Models.TransportViewModel

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Новый транспорт</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Згорнути/ Разгорнути">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                @using (Html.BeginForm())
                {
                    <div class="form-group">
                        <label>Код</label>
                        @Html.TextBoxFor(_ => _.Code, new { @class = "form-control", required = "", pattern = ".{3,}", title = "Код має бути не менш ніж 3 символи" })
                        @Html.ValidationMessageFor(_ => _.Code, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Тип транспорта</label>
                        @Html.DropDownListFor(_ => _.Type.Id, (SelectList)ViewBag.TypeId, new { id = "transportType", @class = "form-control", @required = "" })
                        @Html.ValidationMessageFor(_ => _.Code, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Маршрут</label>
                        @Html.DropDownListFor(_ => _.Route.Id, (SelectList)ViewBag.RouteId, "Оберіть маршрут", new { id = "transportRoute", @class = "form-control" })
                        @Html.ValidationMessageFor(_ => _.Code, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Зберегти" class="btn btn-su" />
                    </div>
                    <a href="@Url.Action("Index")" class="btn btn-danger">Відміна</a>
                }
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $(function () {
            $("#transportType").change(function () {
                var val = $(this).val();
                var subItems = "<option value=''>Оберіть маршрут</option>";
                $.getJSON("@Url.Action("GetRoutes","Transports")", {type:val} ,function (data) {
                    $.each(data,function(index,item) {
                        subItems += "<option value='" + item.Id + "'>" + item.Name + "</option>";
                    });
                    $("#transportRoute").html(subItems);
                });
            });
        });
    </script>
}

RKAdmin/Views/Transports/Details.cshtml
@{
    ViewBag.Title = "Траспорт";
    ViewBag.Subtitle = "";
}

@model RKAdmin.Models.TransportTypeViewModel

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Транспорт #@Model.Id</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Згорнути/ Разгорнути">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Назва</label>
                    @Html.TextBoxFor(_ => _.Name, new { @class = "form-control", @readonly = "" })
                </div>
            </div>
        </div>
    </div>
</div>

RKAdmin/Views/Transports/Edit.cshtml
@{
    ViewBag.Title = "Транспорт";
    ViewBag.Subtitle = "";
}

@model RKAdmin.Models.TransportViewModel

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Транспорт #@Model.Id</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Згорнути/ Разгорнути">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                @using (Html.BeginForm())
                {
                    @Html.HiddenFor(_ => _.Id)

                    <div class="form-group">
                        <label>Код</label>
                        @Html.TextBoxFor(_ => _.Code, new { @class = "form-control", required = "", pattern = ".{3,}", title = "Код має бути не мень ніж 3 символи" })
                        @Html.ValidationMessageFor(_ => _.Code, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Тип транспорта</label>
                        @Html.DropDownListFor(_ => _.Type.Id, (SelectList)ViewBag.TypeId, new { id = "transportType", @class = "form-control", required = "" })
                        @Html.ValidationMessageFor(_ => _.Code, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Маршрут</label>
                        @Html.DropDownListFor(_ => _.Route.Id, (SelectList)ViewBag.RouteId, "Оберіть маршрут", new { id = "transportRoute", @class = "form-control" })
                        @Html.ValidationMessageFor(_ => _.Code, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Зберегти" class="btn btn-success" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script type="text/javascript">
        $(function () {
            $("#transportType").change(function () {
                var val = $(this).val();
                var subItems = "<option value=''>Оберіть маршрут</option>";
                $.getJSON("@Url.Action("GetRoutes","Transports")", {type:val} ,function (data) {
                    $.each(data,function(index,item) {
                        subItems += "<option value='" + item.Id + "'>" + item.Name + "</option>";
                    });
                    $("#transportRoute").html(subItems);
                });
            });
        });
    </script>
}

RKAdmin/Views/Transports/Index.cshtml
@{
    ViewBag.Title = "Транспорт";
    ViewBag.Subtitle = "";
}

@model List<RKAdmin.Models.TransportViewModel>

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Список транспорта</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Згорнути/ Разгорнути">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <a href="@Url.Action("Add")" class="btn btn-success">Додати</a>
        <br />
        <br />
        <table id="table" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Код</th>
                    <th>Маршрут</th>
                    <th>Тип транспорта</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.Code</td>
                    <td>@(item.Route?.Name)</td>
                    <td>@item.Type.Name</td>
                    <td>
                        @*<a href="@Url.Action("Details", new {id = item.Id})" class="btn btn-default btn-xs"><i class="icon ion-eye"></i></a>*@
                        <a href="@Url.Action("Edit", new {id = item.Id})" class="btn btn-default btn-xs"><i class="icon ion-edit"></i></a>
                        <button onclick="deleteItem(@item.Id)" class="btn btn-danger btn-xs"><i class="icon ion-close"></i></button>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section styles
{
    <link rel="stylesheet" href="~/assets/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/sweetalert.css">
}


@section scripts
{
    <script src="~/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/js/dataTables.bootstrap.min.js"></script>
    <script src="~/assets/js/sweetalert.min.js"></script>

    <script>
        $('#table').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Ukrainian.json"
            }
        });

        function deleteItem(id) {
            swal({
                    title: "Ви впевнені?",
                    text: "Цю дію не можливо відмінити!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "Так, видалити!",
                    cancelButtonText: "Ні!"
                },
                () => {
                    $.post('@Url.Action("Delete")', { "id": id }, () => { window.location.reload(); })
                        .fail(() => {
                            swal({
                                title: "Помилка",
                                text:
                                    "Цю дію неможливо виконати зараз. Можливо цей елемент використовується у іншому місці",
                                type: "error",
                                showCancelButton: true,
                                showConfirmButton: false,
                                cancelButtonText: "Добре"
                            });
                        });
                });
        }
    </script>

}