RKAdmin/Controllers/IncidentsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DataModel;
using DataModel.Models;
using DataModel.Models.RozumnaKraina;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using RKAdmin.Models;

namespace RKAdmin.Controllers
{
    [Authorize(Roles = "Адміністратор, Диспетчер, Майстер")]
    public class IncidentsController: BaseController
    {
        private UserManager<ApplicationUser> _userManager;

        public IncidentsController(SkargaBotContext db, UserManager<ApplicationUser> userManager) : base(db)
        {
            _userManager = userManager;
        }

        public ActionResult Index()
        {
            return RedirectToAction("All");
        }

        [HttpPost]
        public async Task<ActionResult> PostMessage(IncidentViewModel model)
        {
            var incident = await Db.RKDIncidents.Include(_ => _.User).FirstOrDefaultAsync(_ => _.Id == model.Id);

            if (incident == null)
                return HttpNotFound();

            var message = new IncidentMessage
            {
                Text = model.NewMessage.Text,
                SenderId = User.Identity.GetUserId(),
                IncidentId = model.Id
            };

            Db.IncidentMessages.Add(message);
            await Db.SaveChangesAsync();

            var files = Request.Files;
            using (var client = new HttpClient())
            {
                using (var content = new MultipartFormDataContent())
                {
                    foreach (string file in files)
                    {
                        using (var ms = new MemoryStream())
                        {
                            var postedFile = Request.Files[file];
                            postedFile.InputStream.CopyTo(ms);
                            var streamContent = new ByteArrayContent(ms.ToArray());
                            streamContent.Headers.ContentType = new MediaTypeHeaderValue(postedFile.ContentType);
                            streamContent.Headers.ContentLength = postedFile.ContentLength;
                            streamContent.Headers.Add("Content-Disposition", "form-data; name=\"" + file + "\"; filename=\"" + postedFile.FileName + "\"");
                            content.Add(streamContent, "file", postedFile.FileName);
                        }
                    }

                    await client.PostAsync(MvcApplication.ApiHost + "/api/rk/files/post/message/" + message.Id, content);
                }
            }            

            if (incident.EnableNotifications)
            {
                await EmailHelper.SendMessageEmail(incident, message);
            }

            return RedirectToAction("Incident", new {id = model.Id});
        }

        public async Task<ActionResult> My()
        {
            
            var model = await Db.RKDIncidents
                .Include(_ => _.AssignedUser)
                .Include(_ => _.User)
                .Include(_ => _.TransportRoute)
                .Include(_ => _.Relations.Select(r => r.IncidentType))
                .Where(_ => _.UserId == CurrentUserId || _.AssignedUserId == CurrentUserId)
                .Select(_ => new
                {
                    _.Id,
                    AssignedUser = new
                    {
                        _.AssignedUser.Name,
                        _.AssignedUser.UserName,
                        Role = Db.Roles.FirstOrDefault(r => r.Id == _.AssignedUser.Roles.FirstOrDefault().RoleId)
                    },
                    User = new
                    {
                        _.User.Name,
                        _.User.UserName,
                        Role = Db.Roles.FirstOrDefault(r => r.Id == _.User.Roles.FirstOrDefault().RoleId)
                    },
                    _.TransportType,
                    _.TransportRoute,
                    _.CraetedAt,
                    _.State,
                    IncidentTypes = _.Relations.Select(r => r.IncidentType)
                })
                .ProjectToListAsync<IncidentViewModel>();

            return View(model);
        }

        public async Task<ActionResult> Filter(int[] incidentType, int? route, int? trasportType)
        {
            if (incidentType?.Length == 0 && route == null && trasportType == null)
                return RedirectToAction("Index");

            var query = Db.RKDIncidents
                .Include(_ => _.AssignedUser.Roles)
                .Include(_ => _.User.Roles)
                .Include(_ => _.TransportRoute)
                .Include(_ => _.Relations.Select(r => r.IncidentType));

            if (incidentType?.Length > 0)
            {
                query = query.Where(_ => _.Relations.Select(r => r.IncidentTypeId).Any(i => incidentType.Contains(i)));
            }

            if (route != null)
            {
                query = query.Where(_ => _.TransportRouteId == route);
            }

            if (trasportType != null)
            {
                query = query.Where(_ => _.TransportTypeId == trasportType);
            }

            var model = await query.Select(_ => new
            {
                _.Id,
                AssignedUser = new
                {
                    _.AssignedUser.Id,
                    _.AssignedUser.Name,
                    _.AssignedUser.UserName,
                    Role = Db.Roles.FirstOrDefault(r => r.Id == _.AssignedUser.Roles.FirstOrDefault().RoleId)
                },
                _.TransportType,
                _.TransportRoute,
                _.CraetedAt,
                _.State,
                _.DeadlineDate,
                _.DeadlineState,
                IncidentTypes = _.Relations.Select(r => r.IncidentType),
                User = new
                {
                    _.User.Id,
                    _.User.Name,
                    _.User.UserName,
                    Role = Db.Roles.FirstOrDefault(r => r.Id == _.User.Roles.FirstOrDefault().RoleId)
                }
            }).ProjectToListAsync<IncidentViewModel>();

            return View("All", model);
        }

        public async Task<ActionResult> All()
        {
            var model = await Db.RKDIncidents
                .Include(_ => _.AssignedUser.Roles)
                .Include(_ => _.User.Roles)
                .Include(_ => _.TransportRoute)
                .Include(_ => _.Relations.Select(r => r.IncidentType))
                .Select(_ => new
                {
                    _.Id,
                    AssignedUser = new
                    {
                        _.AssignedUser.Id,
                        _.AssignedUser.Name,
                        _.AssignedUser.UserName,
                        Role = Db.Roles.FirstOrDefault(r => r.Id == _.AssignedUser.Roles.FirstOrDefault().RoleId)
                    },
                    _.TransportType,
                    _.TransportRoute,
                    _.CraetedAt,
                    _.State,
                    _.DeadlineDate,
                    _.DeadlineState,
                    IncidentTypes = _.Relations.Select(r => r.IncidentType),
                    User = new
                    {
                        _.User.Id,
                        _.User.Name,
                        _.User.UserName,
                        Role = Db.Roles.FirstOrDefault(r => r.Id == _.User.Roles.FirstOrDefault().RoleId)
                    }
                })
                .ProjectToListAsync<IncidentViewModel>();

            return View(model);
        }

        public async Task<ActionResult> SelfAssign(int id)
        {
            var incident = await Db.RKDIncidents.FirstOrDefaultAsync(_ => _.Id == id);

            if (incident == null)
                return HttpNotFound();

            incident.AssignedUserId = User.Identity.GetUserId();
            Db.SaveChanges();

            incident = await Db.RKDIncidents.Include(_ => _.AssignedUser).FirstOrDefaultAsync(_ => _.Id == id);
            await EmailHelper.SendAssignedEmail(incident);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Incident(int id)
        {
            var incident = await Db.RKDIncidents
                .Include(_ => _.AssignedUser)
                .Include(_ => _.User)
                .Include(_ => _.TransportRoute)
                .Include(_ => _.Relations.Select(r => r.IncidentType))
                .Where(_ => _.Id == id)
                .Select(_ => new
                {
                    _.Id,
                    _.AssignedUser,
                    _.TransportType,
                    _.TransportRoute,
                    _.Transport,
                    _.User,
                    _.CraetedAt,
                    _.State,
                    _.Images,
                    _.Latitude,
                    _.Longitude,
                    _.Description,
                    _.Messages,
                    _.DeadlineDate,
                    _.DeadlineState,
                    IncidentTypes = _.Relations.Select(r => r.IncidentType)
                })
                .ProjectToSingleOrDefaultAsync<IncidentViewModel>();

            if (incident == null)
                return HttpNotFound();

            var roleIds = Db.Roles.Where(_ => _.Name == "Диспетчер" || _.Name == "Майстер").Select(_ => _.Id);
            ViewBag.Users = await _userManager.Users.Where(u => u.Roles.Any(_ => roleIds.Contains(_.RoleId))).Select(_ => new SelectListItem
            {
                Text = _.Name +  "(" + _.UserName + ")",
                Value = _.Id
            }).ToListAsync();

            return View(incident);
        }

        [HttpPost]
        public async Task<ActionResult> Incident(IncidentViewModel model)
        {

RKAdmin/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DataModel;
using DataModel.Models.RozumnaKraina;
using Microsoft.AspNet.Identity;
using RKAdmin.Models;

namespace RKAdmin.Controllers
{
    [Authorize(Roles = "Адміністратор, Диспетчер, Майстер")]
    public class OrdersController: BaseController
    {
        public OrdersController(SkargaBotContext db) : base(db)
        {
        }

        public ActionResult Index()
        {
            return RedirectToAction("My");
        }

        [HttpPost]
        public ActionResult EditWorkRow(OrderWorkViewModel model)
        {
            var item = Db.OrderWorks.Find(model.Id);
            if (item == null)
                return HttpNotFound();

            var order = Db.Orders.Find(item.OrderId);
            var oldSum = item.Cost * item.Count * item.Time;
            var newsum = model.Cost * model.Count * model.Time;

            Db.Entry(item).CurrentValues.SetValues(model);
            item.OrderId = order.Id;

            order.OrderSum += newsum - oldSum;

            Db.SaveChanges();
            return new EmptyResult();
        }

        [HttpPost]
        public ActionResult EditItemRow(OrderItemViewModel model)
        {
            var item = Db.OrderItems.Find(model.Id);
            if (item == null)
                return HttpNotFound();

            var order = Db.Orders.Find(item.OrderId);
            var oldSum = item.Cost * item.Count;
            var newsum = model.Cost * model.Count;

            Db.Entry(item).CurrentValues.SetValues(model);
            item.OrderId = order.Id;

            order.OrderSum += newsum - oldSum;

            Db.SaveChanges();
            return new EmptyResult();
        }

        [HttpPost]
        public async Task<ActionResult> DeleteItem(int id)
        {
            var item = Db.OrderItems.Find(id);
            if (item == null)
                return HttpNotFound();

            var order = Db.Orders.Find(item.OrderId);
            order.OrderSum -= item.Cost * item.Count;

            Db.OrderItems.Remove(item);
            await Db.SaveChangesAsync();
            return new EmptyResult();
        }

        [HttpPost]
        public async Task<ActionResult> DeleteWork(int id)
        {
            var item = Db.OrderWorks.Find(id);
            if (item == null)
                return HttpNotFound();

            var order = Db.Orders.Find(item.OrderId);
            order.OrderSum -= item.Cost * item.Count;

            Db.OrderWorks.Remove(item);
            await Db.SaveChangesAsync();
            return new EmptyResult();
        }

        public async Task<ActionResult> My()
        {
            var model = await Db.Orders
                .Include(_ => _.OrderWorks)
                .Include(_ => _.OrderItems)
                .Include(_ => _.User)
                .Include(_ => _.AssignedUser)
                .Where(_ => _.AssignedUserId == CurrentUserId || _.UserId == CurrentUserId)
                .ProjectToListAsync<OrderViewModel>();

            return View(model);
        }


        public async Task<ActionResult> All()
        {
            var model = await  Db.Orders
                .Include(_ => _.OrderWorks)
                .Include(_ => _.OrderItems)
                .Include(_ => _.User)
                .Include(_ => _.AssignedUser)
                .ProjectToListAsync<OrderViewModel>();

            return View(model);
        }

        public async Task<ActionResult> Order(int id)
        {
            var model = await Db.Orders
                .Include(_ => _.OrderWorks)
                .Include(_ => _.OrderItems)
                .Include(_ => _.User)
                .Include(_ => _.AssignedUser)
                .ProjectToFirstOrDefaultAsync<Order, OrderViewModel>(_ => _.Id == id);

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = await Db.Orders
                .Include(_ => _.OrderWorks)
                .Include(_ => _.OrderItems)
                .Include(_ => _.User)
                .Include(_ => _.AssignedUser)
                .ProjectToFirstOrDefaultAsync<Order, OrderViewModel>(_ => _.Id == id);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(OrderViewModel model)
        {
            var order = Db.Orders.Find(model.Id);
            if (order == null)
                return HttpNotFound();

            var entity = Mapper.Map<Order>(model);
            entity.AssignedUserId = order.AssignedUserId;
            entity.UserId = order.UserId;
            entity.CreatedAt = order.CreatedAt;
            entity.IncidentId = order.IncidentId;
            entity.OrderSum = order.OrderSum;

            decimal sum = 0;
            if (model.OrderItems != null)
            {
                var itemsSum = model.OrderItems.Sum(_ => _.Cost * _.Count);
                sum += itemsSum;
            }

            if (model.OrderWorks != null)
            {
                var worksSum = model.OrderWorks.Sum(_ => _.Count * _.Cost * _.Time);
                sum += worksSum;
            }

            entity.OrderSum += sum;
            Db.Entry(order).CurrentValues.SetValues(entity);

            entity.OrderItems.ForEach(_ =>
            {
                _.OrderId = order.Id;
                Db.OrderItems.Add(_);
            });
            entity.OrderWorks.ForEach(_ =>
            {
                _.OrderId = order.Id;
                Db.OrderWorks.Add(_);
            });

            await Db.SaveChangesAsync();
            return RedirectToAction("Order", new {id = order.Id});
        }

        public ActionResult Create(int incidentId)
        {
            var model = new OrderViewModel {IncidentId = incidentId};
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(OrderViewModel model)
        {
            var entity = Mapper.Map<Order>(model);
            entity.CreatedAt = TimeZoneHelper.GetFleDateTime();
            entity.UserId = User.Identity.GetUserId();

            //var dispatcher = Db.Users.Include(_ => _.Roles).FirstOrDefault(_ =>
            //    _.Roles.Any(r => r.RoleId == Db.Roles.FirstOrDefault(rr => rr.Name == "Диспетчер").Id));

            entity.AssignedUserId = User.Identity.GetUserId();

            if (model.OrderItems != null)
            {
                var itemsSum = model.OrderItems.Sum(_ => _.Cost * _.Count);
                entity.OrderSum += itemsSum;
            }

            if (model.OrderWorks != null)
            {
                var worksSum = model.OrderWorks.Sum(_ => _.Count * _.Cost * _.Time);
                entity.OrderSum += worksSum;
            }

            Db.Orders.Add(entity);
            Db.SaveChanges();
            return RedirectToAction("My");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            var item = await Db.Orders.Include(_ => _.OrderWorks).Include(_ => _.OrderItems).SingleOrDefaultAsync(_ => _.Id == id);

            if (item == null)
                return HttpNotFound();


            Db.OrderWorks.RemoveRange(item.OrderWorks);
            Db.OrderItems.RemoveRange(item.OrderItems);
            Db.Orders.Remove(item);
            await Db.SaveChangesAsync();
            return new EmptyResult();
        }
    }
}

RKAdmin/Views/Incidents/Incident.cshtml
@{
    ViewBag.Title = "Інциденти";
    ViewBag.Subtitle = "Деталі інцидента";
}

@using System.Globalization
@model RKAdmin.Models.IncidentViewModel

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Інцидент #@Model.Id</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Згорнути/ Разгорнути">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Создан</label>
                    <input readonly value="@Model.CraetedAt.ToString("g")" class="form-control" />
                </div>

                @if (Model.TransportRoute != null)
                {
                    <div class="form-group">
                        <label>Маршрут</label>
                        <input readonly value="@Model.TransportRoute.Name (@Model.TransportRoute.StartStation - @Model.TransportRoute.StopStation)" class="form-control" />
                    </div>
                }

                <div class="form-group">
                    <label>Транспортний засіб</label>
                    <input readonly value="@(Model.Transport?.Code ?? "Не вказано номер ТЗ")" class="form-control" />
                </div>

                <div class="form-group">
                    <label>Типи інциденту</label>
                    <input readonly value="@string.Join(", ", Model.IncidentTypes.Select(_ => _.Name))" class="form-control" />
                </div>

                <div class="form-group">
                    <label>Від</label>
                    <input readonly value="@(Model.User?.Name ?? "Аононимно")" class="form-control" />
                </div>

                <div class="form-group">
                    <label>Опис</label>
                    <textarea readonly class="form-control">@Model.Description</textarea>
                </div>

                <hr />

                @if (User.IsInRole("Адміністратор") || User.IsInRole("Диспетчер"))
                {
                    <h4>Редактирование информации</h4>
                    using (Html.BeginForm())
                    {
                        @Html.HiddenFor(_ => _.Id)

                        <div class="form-group">
                            <label>Вiдповiдальний</label>
                            @Html.DropDownListFor(_ => _.AssignedUser.Id, (List<SelectListItem>)ViewBag.Users, new { @class = "form-control" })
                            @Html.ValidationMessageFor(_ => _.State, "", new { @class = "text-danger" })
                        </div>

                        <div class="row">
                            <div class="col-md-10">
                                <div class="form-group">
                                    <label>Статус</label>
                                    @Html.EnumDropDownListFor(_ => _.State, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(_ => _.State, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>Дедлайн</label>
                                    <a class="btn btn-default form-control" data-toggle="modal" data-target="#exampleModal"><i class="fa fa-calendar"></i></a>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Зберегти" class="btn btn-success" />
                        </div>

                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Установка дедлайна</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Статус</label>
                                                    @Html.EnumDropDownListFor(_ => _.DeadlineState, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(_ => _.DeadlineState, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Дата дедлайна:</label>
                                                    <div class="input-group date">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-calendar"></i>
                                                        </div>
                                                        @Html.TextBoxFor(_ => _.DeadlineDate, "{0:dd.MM.yyyy}", new { @class = "form-control pull-right datepicker" })
                                                    </div>
                                                    <!-- /.input group -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Ок</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else if (User.IsInRole("Майстер"))
                {

                    <div class="form-group">
                        <a href="@Url.Action("SelfAssign", "Incidents", new {id = Model.Id})" class="btn btn-success">Здробити віодповідальним себе</a>
                    </div>

                    <div class="form-group">
                        <a href="@Url.Action("Create", "Orders", new {incidentId = Model.Id})" class="btn btn-info">Заказ-наряд</a>
                    </div>
                }
            </div>
            <div class="col-md-6">
                <div id="gmap" style="height: 350px; width: 100%; margin-top: 10px"></div>
                @if (Model.Images?.Count > 0)
                {
                    <hr />
                    <h4>Фото інцидента</h4>
                    <div id="images" data-slick='{"slidesToShow": 6, "slidesToScroll": 6}' style="margin-left: 15px; margin-right: 15px">
                        @foreach (var image in Model.Images)
                        {
                            <img class="img-item" height="100" src="//api.rozumnakrayina.com.ua/api/rk/files/getfile?id=@image.Id" />
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Повідомлення по інциденту</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Згорнути/ Разгорнути">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        @if (User.IsInRole("Адміністратор") || User.IsInRole("Диспетчер"))
        {
            using (Html.BeginForm("PostMessage", "Incidents", FormMethod.Post, new {enctype = "multipart/form-data"}))
            {
                @Html.HiddenFor(_ => _.Id)

                <div class="form-group">
                    <label>Нове повідомлення</label>
                    @Html.TextAreaFor(_ => _.NewMessage.Text, new { @class = "form-control", required = "" })
                    @Html.ValidationMessageFor(_ => _.NewMessage.Text, "", new { @class = "text-danger" })
                </div>

                <div class="file-loading">
                    <input id="input-b6" name="input-b6[]" type="file" multiple>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Відправити" class="btn btn-info" />
                </div>
            }
            <hr />
        }

        @if (Model.Messages.Count > 0)
        {
            foreach (var message in Model.Messages)
            {
                <div class="callout" style="border-left: 5px solid #d0021b;">
                    <h5> <b>#@message.Id. Від: @message.Sender.Name. Дата: @message.PostDate</b></h5>

                    <p>@message.Text</p>
                    <div id="images" data-slick='{"slidesToShow": 12, "slidesToScroll": 12}' style="margin-left: 15px; margin-right: 15px">
                        @foreach (var image in message.Images)
                        {
                            <img class="img-item" height="50" src="@MvcApplication.ApiHost/api/rk/files/getfile?id=@image.Id" />
                        }
                    </div>
                </div>
            }
        }
        else
        {
            <p class="text-center">Зараз немає повідомлень по цьому інциденту</p>
        }
    </div>
</div>

<!-- The Modal -->
<div id="img-modal" class="img-modal">

    <!-- The Close Button -->
    <span class="close">&times;</span>

    <!-- Modal Content (The Image) -->
    <img class="img-modal-content" id="modal-img">
</div>




@section styles
{
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css" />
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css" />
    <link rel="stylesheet" type="text/css" href="~/assets/css/gallery.css" />
    <link rel="stylesheet" href="~/assets/css/bootstrap-datepicker.min.css">
    <link href="~/assets/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />

}

@section scripts
{
    <!-- Google Maps API Js -->
    <script src="https://maps.google.com/maps/api/js?v=3&key=AIzaSyBIn9xNcphoBCZRWIDNNPUYtAiP3qU07_8"></script>
    <!-- GMaps PLugin Js -->
    <script src="~/assets/js/gmaps.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js"></script>
    <script src="~/assets/js/bootstrap-datepicker.min.js"></script>
    <script src="~/assets/locales/bootstrap-datepicker.ru.min.js"></script>
    <script src="~/assets/js/fileinput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="~/assets/js/locales/ru.js"></script>

    <script>
        var map = new GMaps({
            div: '#gmap',
            zoom: 12,
            lat: 48.458124202908905,
            lng: 35.03414511680603
        });

        var modal = $("#img-modal");
        var modalImg = $("#modal-img");

        var span = $(".close");

        span.on('click', () => {
            modal.hide();
        });

        $(".img-item").on('click',
            (e) => {
                var src = $(e.target).attr('src');
                modalImg.attr('src', src);
                modal.show();
            });

        $(() => {
            var lat = @Model.Latitude.ToString(CultureInfo.InvariantCulture);
            var lng = @Model.Longitude.ToString(CultureInfo.InvariantCulture);
            map.setCenter(lat, lng);
            map.addMarker({
                lat: lat,
                lng: lng
            });

            $("#images").slick();

            //Date picker
            $('.datepicker').datepicker({
                autoclose: true,
                format: 'dd.mm.yyyy'
            });

            $("#input-b6").fileinput({
                showUpload: false,
                dropZoneEnabled: false,
                maxFileCount: 10,
                mainClass: "input-group-lg",
                language: "ru",
                allowedFileExtensions: ["jpg", "png"]
            });

        });
    </script>
}